- hosts: setup
  become: yes
  tasks:
    - name: Install epel-release and dnf config manager
      dnf:
        name: epel-release
        name: dnf-plugins-core
        state: present

    - name: Enable crb
      command: dnf config-manager --set-enabled crb

    - name: Add Docker repo
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker and plugins
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add docker user
      user:
        name: docker
        state: present

    - name: Create /home/docker directory
      file:
        path: /home/docker
        state: directory
