- hosts: setup:&docker
  become: yes
  tasks:
    - name: install Basic tools
      dnf:
        name: 
          - dnf-plugins-core
          - nano
        state: present
    - name: Install epel-release
      dnf:
        name: epel-release
        state: present

    - name: Enable crb
      command: dnf config-manager --set-enabled crb

    - name: Add Docker repo
      command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker and plugins
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add docker user
      user:
        name: docker
        state: present
        create_home: true
        
    - name: enable and start docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
